#ifndef LIBXSMM_VERSION_H
#define LIBXSMM_VERSION_H

#define LIBXSMM_CONFIG_VERSION "1.16.1-1197"
#define LIBXSMM_CONFIG_BRANCH "master"
#define LIBXSMM_CONFIG_VERSION_MAJOR 1
#define LIBXSMM_CONFIG_VERSION_MINOR 16
#define LIBXSMM_CONFIG_VERSION_UPDATE 1
#define LIBXSMM_CONFIG_VERSION_PATCH 1197
#define LIBXSMM_CONFIG_BUILD_DATE 20210315

#endif

